### ISSUE TITLE
Link to BountySource page so that cooperation is evident

### ISSUE THREAD

**Issue by patcon** [unicefuganda/edtrac#2]
Just thinking that linking the fundraiser page from the repo would give contributors the confidence that the two efforts are connected, despite the different apparent owners.

https://www.bountysource.com/fundraisers/455-edutrac

**Comment by patcon** [comment]
Also, while I'm at it, you should post something on hackernews :)

**Comment by ewheeler** [comment]
@patcon efforts are not connected -- this is not the same edutrac that your link references
